[package]
name = "vgui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
gpui.workspace = true
vgui-css.workspace = true
vgui-view.workspace = true
vgui-tailwind.workspace = true

[dev-dependencies]
trybuild = "1"
