[package]
name = "vgui-shadcn"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "shadcn-style components for vgui"
keywords.workspace = true
categories.workspace = true

[dependencies]
vgui.workspace = true
gpui.workspace = true
